import streamlit as st
option = st.selectbox(
     'Presentas alguno de estos sintomas?',
     ('Llagas', 'Hinchazon', 'Berrugas', 'Irritacion o Enrojecimiento'))
if 'Llagas' in option:
     st.write('Las Llagas son uno de los sintomas carcaterisiticos de la sifilis; La Silifis es una infeccion bacteriana causada por Treponema pallidum, la principal causa de trasnmision es por Contacto Sexual con alguna persona infectada,ya sea vaginal, anal u oral, pero tambien y de fomra menos comun ,es mediente el contacto con una lesion activa como las que se podrian presentar en la boca y al darse un beso se transmitiria, tambien existe la probabilidad de trasnmision de madre a hijo durante el embarazo o parto,todo esto mediente el contacto de las llagas con la piel o membranas mucosas. Aunque es de condsideracion señalar que no es probable que se contagie mendiente el uso de tasas de baño, ropa, piciinas, jacuzzis por mencionar algunos ejemplos. Los sintomas mas comunes es la aparicion de Llagas indoloras en boca, recto o genitales . ¿El tratamiento? es simple existen ocasiones en que los contagios pueden curarse con una sola dosis del antibiotico recomendado por tu medico, en este caso en caso de presentar algun sintoma acude inmenditamente con tu medico, para evitar complicaciones a largo plazo las cuales pueden dañar gravemente a organos como el corazon o cerebro incluso algunos otros. ¡POR FAVOR, CHECATE!')
if 'Hinchazon' in option:
     st.write('La hinchazon en pene o testiculos puede considerarse como uno de los sintomas carateristicos de la Blenorragia o Gonorrea, esta infeccion de trasmision sexual que afecta tanto hombres y mujeres causada por la bacteria Neisseria gonorrhoeae y puede ser adquirida tanto por sexo vaginal, anal u oral y  tambien puede ser trasnmitida por la mama al bebe al momento del parto. Aunque esta infeccion puede expresarse en varias partes del cuerpo como el recto, ojos, garganta y articulaciones aunque generalmente se expresa mas en los genitales, donde se puede presentar secresion en la punta del pene similar al pus, dolor al orinar o hinchazon en los testiculos. Ademas entre sus comlicaciones se puede presentar infertilidad, puedes presentar afectacion en las articulaciones y aumentan la posibilidad de contraer VIH/SIDA. ¿Tratamiento? deberas acudir con tu medico ante sintomas o sospechas de gonorrea y  este te asiganra el tratamiento adecuado tanto para ti como tu pareja. ¡POR FAVOR, CHECATE!')
if 'Berrugas' in option:
     st.write('Cuando se presentan verrugas en los genitales existe una causa probable; El Virus del Papiloma Humano (VPH). Se dice que todas las personas sexualmente activas adquiriran el virus en aqlgun momento de sus vidas. La verrugas ocasionadas por este virus se presentan principalmente en los tejidos humedos de las zonas genitales como el escroto, punta o cuerpo del pene o  ano, aunque tambien se podrian presenta en la boca o garganta de la persona infectada dependiendo del modo de contagio, ademas que en muchas ocasiones las verrugas son tan pequeñas que no logran ser visibles. Presentan un color carne y apariencia a una coliflor, acoplado a esto se puede presentar hinchazon, comezon o malestar en el area e incluso sangrado al momento de mantener relaciones sexuales. dentro de las complicaciones a largo plazo aumenta la posibilidad de presentar cancer tanto pene, boca, ano y garganta ¿Tratamiento? tu medico te recomendara las instrucciones a seguir una vez diagnosticado, ¡POR FAVOR, CHECATE!')  
