import streamlit as st
     
option = st.selectbox(
     'Presentas alguno de estos sintomas?',
     ('Llagas', 'Aumento del flujo vaginal', 'Verrugas', 'Irritacion, Enrojecimiento o Ardor', 'Secrecion Vaginal', 'Olor fetido'))
if 'Llagas' in option:
     st.write('Las Llagas son uno de los sintomas carcaterisiticos de la sifilis; La Silifis es una infeccion bacteriana causada por Treponema pallidum, la principal causa de trasnmision es por Contacto Sexual con alguna persona infectada, ya sea vaginal, anal u oral, pero tambien y de forma menos comun es mediente el contacto con una lesion activa como las que se podrian presentar en la boca y al darse un beso esta se transmitiria, tambien existe la probabilidad de trasnmision de madre a hijo durante el embarazo o parto, todo esto mediente el contacto de las llagas con la piel o membranas mucosas. Aunque es de condsideracion señalarte que no es probable que te contagies mediante el uso de tasas de baño, ropa, piciinas, jacuzzis por mencionar algunos ejemplos. Ademas de aparicion en genitales tambien se puede presesentar llagas indoloras en boca y recto- ¿El tratamiento? es simple existen ocasiones en que los contagios pueden curarse con una sola dosis del antibiotico recomendado por tu medico, en caso de que presentes algun sintoma acude inmenditamente con tu medico a realizar el diagnostico correspondiente, para evitar complicaciones a largo plazo las cuales pueden dañar gravemente a organos como el corazon o cerebro incluso algunos otros. ¡POR FAVOR, CHECATE!')
if 'Aumento del flujo vaginal' in option:
     st.write('El aumento del flujo vaginal puede considerarse como uno de los sintomas carateristicos de la Blenorragia o Gonorrea, esta infeccion de trasmision sexual que afecta tanto hombres y mujeres causada por la bacteria Neisseria gonorrhoeae y puede ser adquirida tanto por sexo vaginal, anal u oral y tambien puede ser trasnmitida en el momento del parto de la madre al bebe. Aunque esta infeccion puede expresarse en varias partes del cuerpo como el recto, ojos, garganta y articulaciones esta se expresa generalmente en los genitales, donde ademas puedes presentar dolor al orinar, sangrado vaginal como despues de tener relaciones sexuales vaginales, ademas de dolor abdominal o pelvico. Ademas entre sus complicaciones existe la posibilidad infertilidad,presentar afectaciones en las articulaciones y aumenta la posibilidad de contraer VIH/SIDA. ¿Tratamiento? deberas acudir con tu medico ante sintomas o sospechas de gonorrea y  este te asiganra el tratamiento adecuado tanto para ti como tu pareja. ¡POR FAVOR, CHECATE!')
if 'Verrugas' in option:
     st.write('Cuando se presentan verrugas en los genitales existe una causa probable; El Virus del Papiloma Humano (VPH). Se dice que todas las personas sexualmente activas adquiriran el virus en algun momento de sus vidas. Existen causas probables de transmision como la practica de sexo vaginal, anal u oral, aunque tambien se transmite por medios de cortes, abrasiones y desgarros. Ademas las personas que son portadoras del VIH o con alguna alteracion en el sistema inmune son aun mas propensas. La verrugas ocasionadas por este virus se presentan principalmente en los tejidos húmedos de las zonas genitales o ano aunque tambien se podrian presentar en la boca o garganta de la persona infectada dependiendo del modo de contagio, presentan un color carne y apariencia a una coliflor, adicional a esto se puede presentar hinchazon, comezón o malestar en el area e incluso sangrado al momento de mantener relaciones sexuales, ademas en muchas ocasiones las verrugas son tan pequeñas que no logran ser visibles. Dentro de las complicaciones a largo plazo aumenta la posibilidad de presentar cancer de cuello uterino boca, ano y garganta ¿Tratamiento? tu medico te recomendara las instrucciones a seguir una vez diagnosticado correctamente y en caso de presentar la infeccion, ¡POR FAVOR, CHECATE!')  
if 'Irritacion, Enrojecimiento, Picazón y Ardor' in option:
     st.write('Este sintoma puede deberse a varias causas como Trichomoniasis ocasionada por el parasito patogeno Tricomonas vaginallis o candidiasis causada por contacto con el hongos vagianles como Candida albicans, ambas presentan enrojecimiento, picazón y sensacion de ardor en los genitales al orinar o mantener relaciones sexuales. En ambos casos este es ocasionado por el contacto sexual vaginal con parejas portadoras de los microoganismos señalados causanttes de las mismas. ¿Tratamiento? en ambos casos necesitaras visitar a tu medico el cual aplicara las prubeas de diagnostico correcto y  en caso de confirmar se aplicara el tratamiento correspondiente dependiendo de la naturaleza del patogeno. ¡POR FAVOR, CHECATE!')
if 'Secrecion Vaginal' in option:
     st.write('Existen fluidos vaginales inusuales que pueden estar relacionados con alguna enfermedad de transmision sexual como por ejemplo fluido de colores como gris, amarillo o verde es caracteristico de la tricomoniasis y tambien puede tener caracteristicas propias de una vaginitis bacteriana, o bien secrecion espesa, blanca e inoloro parecida al queso cotagge que es parte de los sintomas relacionados con la candidiasis, estas infecciones son ocasionadas por distintos microrganismos patogenos y en la mayoria de los casos estas son ocasionados por el contacto sexual vaginal con parejas portadoras de los agentes causantes de las mismas. ¿Tratamiento? En estoscasos necesitaras visitar a tu medico el cual aplicara las pruebas de diagnostico correcto y  en caso de confirmar se aplicara el tratamiento correspondiente dependiendo de la naturaleza del patogeno. ¡POR FAVOR, CHECATE!')
if 'Olor fetido' in option:
     st.write('El olor fetido a "pescado", es uno  de los sintomas mas comunes de las vaginitis bacterianas, estas son ocasionadas principalmente por un desequilibrio en la poblacion bacteriana de la vagina. Ademas de este sintoma tambien es caracteristico de las vaginitis bacteriana comezón vaginal, ardor vaginal o secrecion vaginal de color gris, blanca o verde,  estas ademas de  no ser tratadas correctamente las vaginitis bacterianas traen consigo complicaciones durente el embarazo, enferemedad inflamatorio pelvica o el aumento posibilidad de contraer otras enfermedades de transmision sexual ¿Tratamiento? Primero deberas acudir al medico a que te aplique las herramientas de diagnostico correcto y posterior a eso el te indeicara al tratamiento adecuado para ti')
     
